solon.app:
  name: solon-arch

server.port: 8081

database.db:
  schema: cur_use
  jdbcUrl: "jdbc:mysql://localhost:3306/cur_use?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true"
  driverClassName: "com.mysql.cj.jdbc.Driver"
  username: "root"
  password: "123456"
  maxLifetime: 1000000

# 配置数据源对应的 mybatis 信息（要与 DataSource bean 的名字对上）
mybatis.db:
  typeAliases:    #支持包名 或 类名（大写开头 或 *）//支持 ** 或 * 占位符
    "com.evalcony.model"
  mappers:        #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）//支持 ** 或 * 占位符
    - "com.evalcony.mapper"
    - "classpath:mapper/*.xml"
  configuration:  #扩展配置（要与 MybatisConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapperVerifyEnabled: true #如果为 true，则要求所有 mapper 有 @Mapper 主解
    mapUnderscoreToCamelCase: true

## xxl-job
solon.cloud.xxljob:
  server: "http://localhost:8080/xxl-job-admin"

solon.logging.logger:
  "io.netty.*":
    level: INFO

xxl.job.executor.port: 10000
xxl.job.accessToken: "default_token"

# redission
redis.ds:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      database: 0

# redis
redis.rd:
  server: localhost:6379
  db: 1
